[General]

; Toggle recording conversations to the the Dialogue History log.
bDialogueHistory = 1

; Maximum number of dialogue entries saved. Oldest entries are permanently removed automatically on save when the limit is reached. 0 = Unlimited entries
iEntryLimit = 250

; Dialogue history wont be saved for non persistent NPCs.
bIgnoreNonPersistentNPCs = 1

; Attempts to ignore consecutive duplicate dialogue lines being saved to the history. Eg. The player selects the same dialogue choice twice in a row.
bIgnoreDuplicateLines = 1


[Interface]

; Toggle "Dialogue History" button visibility in the Dialogue/Pause menus.
bShowMenuButton = 1

; Speaker name text color. Accepts systemcolor index (0-5).
; Systemcolor Indexes: 0 = Custom (Set RGB), 1 = HUD, 2 = HUD Alt (Red), 3 = Terminal (Green), 4 = Pip-Boy, 5 = Pause Menu
iPlayerSystemcolor = 0
iPlayerRed = 255
iPlayerGreen = 255
iPlayerBlue = 51
iNPCSystemcolor = 0
iNPCRed = 0
iNPCGreen = 204
iNPCBlue = 255
