[General]
; Enable the Dialogue History feature. Disable if you only want to use the conversation transcript.
bDialogueHistory=1
; Maximum number of dialogue entries saved. Oldest entries are removed automatically on save when the limit is reached. 0 = Unlimited entries
iEntryLimit=100
; Dialogue history wont be saved for non persistent NPCs.
bIgnoreNonPersistentNPCs=1
; Attempts to ignore consecutive duplicate dialogue lines being saved to the history. Eg. The player selects the same dialogue choice twice in a row.
bIgnoreDuplicateLines=1

[Interface]
; Toggle "Dialogue History" button visibility in the Dialog/Pause menus"
bShowMenuButton=1
; Speaker name text color. Accepts systemcolor index (0-5) or 6 character hex color code (Eg. 1ED16B).
; Systemcolor Indexes: 0 = None (White), 1 = HUD, 2 = HUD Alt (Red), 3 = Terminal (Green), 4 = Pip-Boy, 5 = Pause Menu
sNPCColor=00CCFF
sPlayerColor=FFFF33